// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAj18Dc7HQQLF4Cy-OeBD74my-RhHF5hk',
    appId: '1:1020860362947:web:17d4721a45faca2d4bf276',
    messagingSenderId: '1020860362947',
    projectId: 'exam-mobile-83533',
    authDomain: 'exam-mobile-83533.firebaseapp.com',
    storageBucket: 'exam-mobile-83533.appspot.com',
    measurementId: 'G-1145BWGBXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfWgsY-v0A3fbH2PT8D-IUJYLcoRlAHo',
    appId: '1:1020860362947:android:30278047937320404bf276',
    messagingSenderId: '1020860362947',
    projectId: 'exam-mobile-83533',
    storageBucket: 'exam-mobile-83533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-rpn9-oDcWW5xiluV9Lw7hN_lPpRbPA',
    appId: '1:1020860362947:ios:943d8d104c8103314bf276',
    messagingSenderId: '1020860362947',
    projectId: 'exam-mobile-83533',
    storageBucket: 'exam-mobile-83533.appspot.com',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-rpn9-oDcWW5xiluV9Lw7hN_lPpRbPA',
    appId: '1:1020860362947:ios:943d8d104c8103314bf276',
    messagingSenderId: '1020860362947',
    projectId: 'exam-mobile-83533',
    storageBucket: 'exam-mobile-83533.appspot.com',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAj18Dc7HQQLF4Cy-OeBD74my-RhHF5hk',
    appId: '1:1020860362947:web:91e11805d507b8684bf276',
    messagingSenderId: '1020860362947',
    projectId: 'exam-mobile-83533',
    authDomain: 'exam-mobile-83533.firebaseapp.com',
    storageBucket: 'exam-mobile-83533.appspot.com',
    measurementId: 'G-C2VFR3LGP2',
  );
}
